source 'https://github.com/CocoaPods/Specs.git'

workspace 'Messenger.xcworkspace'
platform :ios, '12.0'

def shared_pods
    pod 'SlackTextViewController', :path => '../SlackTextViewController.podspec'
    pod 'LoremIpsum'
    pod 'TTGTagCollectionView'
end

target 'Messenger-Programatic' do
    shared_pods
end

target 'Messenger-Storyboard' do
    shared_pods
end

target 'Messenger-Swift' do
    shared_pods
end

target 'Messenger-iPad-Sheet' do
    shared_pods
end
